web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/var/www/
        - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
  build: .docker/php
  volumes: 
    - .:/var/www/
  environment:
    - XDEBUG_CONFIG=remote_host=host.docker.internal
    - MYSQL_HOST=mysql
    - MYSQL_DBNAME=findYourDistricts
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=findYourDistricts
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password